services:
  cpro-erp-connector:
    container_name: cpro-erp-connector
    build:
      context: './src'
      dockerfile: 'dockerfile'
    restart: 'always'
    volumes:
      - ./src/data:/data
      - ./src/nodes:/cpro-erp-connector/src/nodes
    environment:
      ENVIRONMENT: 'dev' # 'dev' or 'prod'
      EXTERNAL_MODULES_ALLOW_INSTALL: 'true'
      MONGO_SNAPSHOT_STRATEGY: 'collection' # or 'gridfs' for larger files
      MONITOR_API_URL: http://host.docker.internal:8000
    # env_file:
    #   - .env # Use a custom .env file
    ports:
      - "3199:3199"
      - "4840:4840"
    networks:
      - default   

networks:
  default:
volumes:
  erp-connector-monitor: